### PR TITLE
improved readme and created hacs conf

### PR DESCRIPTION
**Pull request by brondum**
A bit needs to be done in HACS repository when if this gets merged.

### CODE REVIEW

**Comment by JonasPed** [comment]
Thanks.

**Comment by brondum** [comment]
I dont know if have permissions to add it to HACS. But i am willing to give it a shot??

**Comment by allanpersson** [comment]
> I dont know if have permissions to add it to HACS. But i am willing to give it a shot??

Only the owner of the addon is allowed to add it to HACS 🙏

**Comment by brondum** [comment]
Ah yeah, then i wont bother. If you have the time @JonasPed 
It should be simple: https://hacs.xyz/docs/publish/include

**Comment by allanpersson** [comment]
A PR with the url and information has to be posted here by @JonasPed https://github.com/hacs/default/ and the integration will be available in HACS

**Pull request merged**
