### PR TITLE
 Updated readme example: "Forecast total kWh price", to include tax on the whole price and not just the tariffs

### PR DESCRIPTION
**Pull request by Runepx4**
Minor correction, so government tax is added to the total price: 1.25 * (raw_electricity_cost+tariffs)

### CODE REVIEW

**Comment by JonasPed** [comment]
Thanks

**Comment by Waseh** [comment]
@Runepx4 Isn't VAT added twice now if the Nordpool integration is set up to include VAT? (which is it by default)

**Comment by Runepx4** [comment]
@Waseh, I was not aware that Nordpool added vat to the price, and could not find it on their homepage. Can you share a link to where you discovered that it was included? 
@runemoennike

**Comment by runemoennike** [comment]
@Runepx4 Hm, it seems the Nordpool integration for HA adds VAT by default, based on the region. It's documented here https://github.com/custom-components/nordpool if you search for "Include VAT".

From looking at the source code, it adds the VAT factor to the sensor name, as the very last part. My Nordpool sensor has `_025` at the end of its name, so I guess that means it does actually include VAT :)

**Comment by JonasPed** [comment]
When configuring the nordpool integration you can select if VAT should be included or not. Unless we have two examples in the README.md file it will be wrong depending on the configuration of the Nordpool integration. 

I will keep the example we have now and add a note that it assumes the Nordpool integration is configured to NOT include VAT.

**Comment by Waseh** [comment]
To avoid unnecessary confusion wouldn't it be better to include an example that aligns with the default behaviour?

**Pull request merged**
